AWSTemplateFormatVersion: "2010-09-09"
Description: "twiter"
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  UserDynamoDBTable:

    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "User"
      AttributeDefinitions:
        - AttributeName: "userid"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "password"
          AttributeType: "S"
        - AttributeName: "nombre"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userid"
          KeyType: "HASH"
        - AttributeName: "username"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      LocalSecondaryIndexes:
        - IndexName: "index_userid_username"
          KeySchema:
            - AttributeName: "userid"
              KeyType: "HASH"
            - AttributeName: "username"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_userid_email"
          KeySchema:
            - AttributeName: "userid"
              KeyType: "HASH"
            - AttributeName: "email"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_userid_password"
          KeySchema:
            - AttributeName: "userid"
              KeyType: "HASH"
            - AttributeName: "password"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_userid_nombre"
          KeySchema:
            - AttributeName: "userid"
              KeyType: "HASH"
            - AttributeName: "nombre"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  TweetDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DependsOn: "UserDynamoDBTable"
    Properties:
      TableName: "Tweet"
      AttributeDefinitions:
        - AttributeName: "idtweet"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "comment"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idtweet"
          KeyType: "HASH"
        - AttributeName: "username"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      LocalSecondaryIndexes:
        - IndexName: "index_idtweet_username"
          KeySchema:
            - AttributeName: "idtweet"
              KeyType: "HASH"
            - AttributeName: "username"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idtweet_comment"
          KeySchema:
            - AttributeName: "idtweet"
              KeyType: "HASH"
            - AttributeName: "comment"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idtweet_date"
          KeySchema:
            - AttributeName: "idtweet"
              KeyType: "HASH"
            - AttributeName: "date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  TweetCommentDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DependsOn: [ "UserDynamoDBTable",  "TweetDynamoDBTable" ]
    Properties:
      TableName: "TweetComment"
      AttributeDefinitions:
        - AttributeName: "idcomment"
          AttributeType: "S"
        - AttributeName: "idtweet"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "comment"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idcomment"
          KeyType: "HASH"
        - AttributeName: "idtweet"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      LocalSecondaryIndexes:
        - IndexName: "idtweet"
          KeySchema:
            - AttributeName: "idcomment"
              KeyType: "HASH"
            - AttributeName: "idtweet"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idcomment_username"
          KeySchema:
            - AttributeName: "idcomment"
              KeyType: "HASH"
            - AttributeName: "username"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idcomment_comment"
          KeySchema:
            - AttributeName: "idcomment"
              KeyType: "HASH"
            - AttributeName: "comment"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idcomment_date"
          KeySchema:
            - AttributeName: "idcomment"
              KeyType: "HASH"
            - AttributeName: "date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  TweetUserReactionDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DependsOn: [ "UserDynamoDBTable",  "TweetDynamoDBTable" ]
    Properties:
      TableName: "TweetUserReaction"
      AttributeDefinitions:
        - AttributeName: "idtweet_user_reaction"
          AttributeType: "S"
        - AttributeName: "idtweet"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "reaction"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idtweet_user_reaction"
          KeyType: "HASH"
        - AttributeName: "idtweet"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      LocalSecondaryIndexes:
        - IndexName: "index_idtweet_user_reaction_idtweet"
          KeySchema:
            - AttributeName: "idtweet_user_reaction"
              KeyType: "HASH"
            - AttributeName: "idtweet"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idtweet_user_reaction_username"
          KeySchema:
            - AttributeName: "idtweet_user_reaction"
              KeyType: "HASH"
            - AttributeName: "username"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idtweet_user_reaction_reaction"
          KeySchema:
            - AttributeName: "idtweet_user_reaction"
              KeyType: "HASH"
            - AttributeName: "reaction"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "index_idtweet_user_reaction_date"
          KeySchema:
            - AttributeName: "idtweet_user_reaction"
              KeyType: "HASH"
            - AttributeName: "date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  CreateUserHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: CreateUserHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.user.CreateUserHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  DeleteUserHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: DeleteUserHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.user.DeleteUserHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: GetUserHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.user.GetUserHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  ListUserHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: ListUserHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.user.ListUserHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  CreateTweetHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: CreateTweetHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweet.CreateTweetHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  DeleteTweet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: DeleteTweetHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweet.DeleteTweetHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  GetTweetHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: GetTweetHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweet.GetTweetHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  ListTweetHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: ListTweetHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweet.ListTweetHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  CreateTweetCommentHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: CreateTweetCommentHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetComment.CreateTweetCommentHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  DeleteTweetCommentHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: DeleteTweetCommentHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetComment.DeleteTweetCommentHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  GetTweetCommentHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: GetTweetCommentHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetComment.GetTweetCommentHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  ListTweetCommentHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: ListTweetCommentHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetComment.ListTweetCommentHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  CreateTweetUserReactionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: CreateTweetUserReactionHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetUserReaction.CreateTweetUserReactionHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  DeleteTweetUserReactionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: DeleteTweetUserReactionHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetUserReaction.DeleteTweetUserReactionHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  GetTweetUserReactionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: GetTweetUserReactionHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetUserReaction.GetTweetUserReactionHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole

  ListTweetUserReactionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 's3://twittertesttesttest/AYGO-ARCHITECTURE-OF-MASSIVELY-DISTRIBUTED-APPLICATIONS-1.0-SNAPSHOT.jar'
      FunctionName: ListTweetUserReactionHandler
      MemorySize: 512
      Handler: co.edu.escuelaing.twitter.handler.tweetUserReaction.ListTweetUserReactionHandler
      Role: 'arn:aws:iam::275101086977:role/LabRole'
      Timeout: 20
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole


  TwitterApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: An API Gateway with a Lambda Integration
      EndpointConfiguration:
        Types:
          - EDGE
      Name: TwitterApi

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt TwitterApi.RootResourceId
      PathPart: 'tweeter'
      RestApiId: !Ref TwitterApi

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET

      Integration:

        ConnectionType: INTERNET
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserHandler.Arn}/invocations'
      OperationName: 'lambda'
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref TwitterApi

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref TwitterApi
      Schema: { }

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      Description: Lambda API Deployment
      RestApiId: !Ref TwitterApi

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      Description: Lambda API Stage v0
      RestApiId: !Ref TwitterApi
      StageName: 'v0'

  